name: 'PROD build'

on:
  push:
    branches:
      - master
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: ".*"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          platforms: linux/amd64,linux/arm64
          target: api
          push: true
          tags: |
            ghcr.io/senergy-platform/ml-trainer:prod
            smartenergyplatform/ml-trainer:prod
            ghcr.io/senergy-platform/ml-trainer:${{ steps.tag_version.outputs.new_tag }}
            smartenergyplatform/ml-trainer:${{ steps.tag_version.outputs.new_tag }}
            ghcr.io/senergy-platform/ml-trainer:latest
            smartenergyplatform/ml-trainer:latest
